build:
	docker-compose build

up:
	docker-compose up -d

down:
	docker-compose down

restart:
	make down
	make up

backend_logs:
	docker logs shadowpay-app-1

nginx_logs:
	docker logs shadowpay-nginx-1
