version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
