version: '3'

services:
  app:
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: .
    restart: always
    volumes:
      - .:/app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
